site_name: Experiment With GitHub Pages
site_url: https://tricerintops.github.io/ExperimentWithGitHubPages/

theme:
  name: material

nav:
  - Home: index.md
  - First File: first_file.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji

# (optional but nice)
repo_url: https://github.com/tricerintops/ExperimentWithGitHubPages
repo_name: ExperimentWithGitHubPages
